image: gitpod/workspace-mysql

ports:
- port: 8888 # drush rs
  onOpen: open-preview
- port: 3000 # yarn start
  onOpen: ignore

tasks:
- name: drush-rs
  before: |
    wget -O drush.phar https://github.com/drush-ops/drush-launcher/releases/latest/download/drush.phar
    mkdir -p ~/.local/bin
    chmod +x drush.phar && mv drush.phar ~/.local/bin/drush
    cd /workspace/gswebplay && composer install
    chmod +w /workspace/gswebplay/web/sites/default/
    cp -r /workspace/gswebplay/config/provision/*.php /workspace/gswebplay/web/sites/default/
  init: composer update
  command: drush rs 0.0.0.0
  openMode: split-left

- name: drush
  openMode: split-right

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: true
    addBadge: false
    addLabel: false
