# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
if [ -f /vagrant/.env ]; then
	set -o allexport; source /vagrant/.env; set +o allexport
fi
PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH=/home/vagrant/.config/composer/vendor/bin/:$PATH
alias composer="COMPOSER_MEMORY_LIMIT=-1 composer"
chmod 400 ~/.ssh/gsweb18.pem
